apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sauron

resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml

commonLabels:
  app: sauron
  version: v1

images:
  - name: sauron
    newTag: latest
