apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sauron-data-pvc
  namespace: sauron
  labels:
    app: sauron
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
